# 这些是支持的资助平台

github: # 你的GitHub用户名
patreon: # 你的Patreon用户名
open_collective: # 你的Open Collective用户名
ko_fi: # 你的Ko-fi用户名
tidelift: # 你的Tidelift平台名称/软件包名称
community_bridge: # 你的Community Bridge项目名称
librebase: # 你的Librebase用户名
issuehunt: # 你的IssueHunt用户名
otechie: # 你的Otechie用户名
custom: # 其他自定义资助链接